import { Montserrat } from 'next/font/google'
import { Metadata } from "next";
import "./globals.css";
import Header from './components/Header'
import { PokemonProvider } from '../store/PokemonStore';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <PokemonProvider>
          <Header/>
          {children}
        </PokemonProvider>
      </body>
    </html>
  );
}
